name: Terraform K8S Deploy

on:
  workflow_dispatch:
    inputs:
      cloud:
        description: "Cloud"
        required: true
        type: choice
        options:
          - GCP
          - AWS
      env_type:
        description: "Environment type"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      env_name:
        description: "K8S environment (cluster) name (only lowercase letters, numbers, and hyphens. Must start with a lowercase letter)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write   # REQUIRED for Workload Identity Federation

env:
  PROJECT_NUMBER: ${{ vars.PROJECT_NUMBER }}
  PROJECT_ID: ${{ vars.PROJECT_ID}}
  TF_VAR_project_id: ${{ vars.PROJECT_ID}}
  TF_VAR_region: ${{ vars.REGION }}
  env_type: ${{ inputs.env_type }}

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/gcp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate K8S environment (cluster) name
        run: |
          NAME="${{ inputs.env_name }}"

          if [[ ! "$NAME" =~ ^[a-z]([-a-z0-9]{0,38}[a-z0-9])?$ ]]; then
            echo "❌ Invalid K8S cluster name"
            echo "Rules:"
            echo " - 1–40 characters"
            echo " - lowercase letters, numbers, hyphens"
            echo " - must start with a letter"
            echo " - must not end with a hyphen"
            exit 1
          fi

          echo "✅ K8S cluster name is valid: $NAME"

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: projects/${{env.PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-terraform-k8s@${{vars.PROJECT_ID}}.iam.gserviceaccount.com

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14

      - name: Debug OIDC token
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"

      - name: Stop workflow
        run: |
          echo "Intentional stop"
          exit 1
######################################
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="prefix=${{ inputs.env_type }}/${{ inputs.env_name }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="env_type=${{ inputs.env_type }}" \
            -var="env_name=${{ inputs.env_name }}" \
            -var-file="./envs/${{ inputs.env_type }}.tfvars" \
            -out=tfplan


      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply \
            -var="env_name=${{ inputs.env_name }}" \
            -var-file="./envs/${{ inputs.env_type }}.tfvars" \
            -auto-approve \
            tfplan

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Get K8S credentials
        run: |
          gcloud container clusters get-credentials \
            ${{ inputs.env_name }} \
            --location $(terraform output -raw location) \
            --project ${{ env.PROJECT_ID }}

      - name: Verify cluster access
        run: |
          kubectl version --client
          kubectl get nodes            