name: Deploy Cluster Tools

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  workflow_dispatch: 
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      cluster_name:
        description: "GKE cluster name (only lowercase letters, numbers, and hyphens. Must start with a lowercase letter)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write   # REQUIRED for Workload Identity Federation

env:
  PROJECT_NUMBER: ${{ vars.PROJECT_NUMBER }}
  PROJECT_ID: ${{ vars.PROJECT_ID}}
  TF_VAR_project_id: ${{ vars.PROJECT_ID}}
  TF_VAR_region: ${{ vars.REGION }}
  ENVIRONMENT: ${{ github.event.inputs.environment }}

jobs:
  terraform:
    name: deploy_cluster_tools
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/gcp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate GKE cluster name
        run: |
          NAME="${{ inputs.cluster_name }}"

          if [[ ! "$NAME" =~ ^[a-z]([-a-z0-9]{0,38}[a-z0-9])?$ ]]; then
            echo "❌ Invalid GKE cluster name"
            echo "Rules:"
            echo " - 1–40 characters"
            echo " - lowercase letters, numbers, hyphens"
            echo " - must start with a letter"
            echo " - must not end with a hyphen"
            exit 1
          fi

          echo "✅ GKE cluster name is valid: $NAME"

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: projects/${{env.PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-terraform@chatgpt1-goland1.iam.gserviceaccount.com
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14
      
      - name: Debug OIDC token
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
      
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="prefix=envs/${{ inputs.environment }}/${{ inputs.cluster_name }}"

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: gke-gcloud-auth-plugin

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials \
            ${{ inputs.cluster_name }} \
            --location $(terraform output -raw location) \
            --project ${{ env.PROJECT_ID }}
      
      #- run: gcloud components list

      - name: Verify cluster access
        run: |
          kubectl version 
          kubectl get nodes            
      
      - name: Install / Upgrade Argo CD
        run: |
          helm upgrade --install argocd \
            oci://ghcr.io/argoproj/argo-helm/argo-cd \
            --namespace argocd \
            --create-namespace \
            --wait \
            --wait-for-jobs \
            --timeout 20m
#           --version 7.7.0 \
#           --set server.service.type=LoadBalancer \

      - name: Verify Argo CD server is ready
        run: |
          kubectl rollout status deployment/argocd-server \
            -n argocd \
            --timeout=5m

      - name: Get Argo CD LoadBalancer address
        run: |
          kubectl get svc argocd-server \
            -n argocd \
            -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
